### ISSUE TITLE
Cannot download Connectivity.EZHex

### ISSUE THREAD

**Issue by hugegit** [jaymzh/concordance#27] opened 2020-10-18 23:27 UTC
I just found out about Concordance and am trying to make it work with my old Harmony 520 remote. I am stuck at the point of trying to obtain/download the Connectivity.EZHex file from logitech.  I have tried on two different Windows 10 machines on Chrome, IE & Firefox, and I have tried adding extensions in Chrome & Forefox to Ignore X-frame headers, but I have never been able to trigger the download. I can log in to the Harmony software but when I click next on "ensure the Harmony 520 can communicate..." I get a blank page that refreshes every few seconds, and no file downloads.

Is there anything else I need to do to get the EZHex file?

Thanks for any assistance...

**Comment by jaymzh** [comment] 2020-10-18 23:36
I can't reproduce this. I logged in, clicked "Update my remote" and then the "Ensure..." page comes up, I click "next" and the blank page comes up (this is normal) and I'm immediately prompted for a download. I'm on Linux with Firefox 81.

**Comment by hugegit** [comment] 2020-10-19 00:06
Wow - thanks so much for the fast reply. A couple thoughts spring up about what could be stopping me from getting the download...

1. Most obvious difference between us is that I'm trying on Windows. The only Linux I have access to is Debian running on some headless servers, so no easy way to run a browser. But I assume others have done this on Windows and downloaded the file successfully...

2. I actually have the regular Harmony software (v7.7) installed on my Windows machines. Could that be stopping the website from thinking it needs to push the EZHex file to me?  (I don't quite see how this could be the case, but I don't really understand the interface between browser & devices)

Thanks again...

**Comment by hugegit** [comment] 2020-10-19 07:44
I booted a laptop with a Debian live DVD, opened Firefox, and successfully downloaded Connectivity.EZHex. Having gone through that process and getting back to your instructions, now I'm not sure how much this gains me, since I have the Windows software to begin with. Does using concordance along with the old web-based config software allow more options in programming a remote than the official Windows software does?  

I'm not complaining by any means - it was a fun plague-time tinkering project and an excuse to mess around with Debian, and I learned how to temporarily convert my old laptop into a Debian box.  And I really do appreciate you responding so quickly to my stumbly post...

Thanks

**Comment by swt2c** [comment] 2020-10-19 13:00
In general, if you're fine with using the official Windows software, Concordance doesn't really buy you much.  It's mostly for platforms like Linux where there is no official software.  Concordance *does* allow you to enter pronto IR codes, which the official software does not.  I think that's probably the main reason people use it on Windows.

**Comment by jaymzh** [comment] 2020-10-19 16:07
Yeah if you have access to Windows, I'd use the official software. It wraps both the website part and the "push the config blob to the remote" part (which is the thing Concordance does). As @swt2c mentioned, it's primarily built for people who can't run the official software because they're on Linux or for some other reason. We have a few users who just really don't like the official software or don't want to limit non-opensource software on their computers as well.

I'm going to close this, but feel free to re-open if you still want to debug Concordance!

**Closed as completed by jaymzh** 2020-10-19 16:07 UTC
