### ISSUE TITLE
Logitech depracting website login. Concordance breakage expected.

### ISSUE THREAD

**Issue by develroo** [jaymzh/concordance#11] opened 2016-04-09 11:08 UTC
Hey,

Title says it all. I am not sure when they decided to but as you can see [here](https://imgur.com/G9RolEB) they are basically forcing all users to use the software either via the desktop of via an 'app' 

Maybe we can hack something together if we can be bothered to reverse the software but to be honest I am starting to think that it is more effort than it is worth. 

What ye think? Is this the end for Linux support for Harmony remotes?

**Comment by jaymzh** [comment] 2016-04-09 21:28
Are you using the new URL we put into the README? The main page has been saying that forever...

**Comment by develroo** [comment] 2016-04-10 01:49
If you mean http://members.harmonyremote.com/EasyZapper then yes. I did try that. I login and it tells me my [client software is not up to date](https://imgur.com/fp543Cp) and then prompts to download Connectivity.EZHex, which is picked up by congruity and that goes ok until the [website error Unable to display content.](https://imgur.com/a/uRSFk)

Now it could just be my remote is incompatible with the site but I know it used to work ok so something is broken. :(

Any ideas?

**Comment by jaymzh** [comment] 2016-04-10 07:37
I just updated my 895 with no problem... what kind of remote is it?

**Comment by develroo** [comment] 2016-04-10 09:28
As you can see from the screenshots it shows up as a 300i. I am not sure if it is a browser issue or a website one. I am using Firefox ESR 45.0.1 on Debian 8. The fact congruity did not throw up any errors is encouraging, but the website might yet still be broken. How to go about debugging this?

**Comment by jaymzh** [comment] 2016-04-10 22:17
Oh - the 300s require mhgui, they don't work with the website.

**Comment by develroo** [comment] 2016-04-11 00:08
Yeah tried that too. Something barfs though.

> mhgui 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 16765, in <lambda>
>     lambda event: event.callable(_event.args, *_event.kw) )
>   File "/usr/bin/mhgui", line 132, in ThreadDoneFunction
>     self.onDoneFunction(bgFuncResult, *self.onDoneFunctionArgs)
>   File "/usr/bin/mhgui", line 603, in LoadDataUI
>     capabilities = self.product.SupportedCapabilities.SupportedCapability
> AttributeError: 'ProductCapabilities' object has no attribute 'SupportedCapability'

That's why I think the website has broken something.

**Comment by jaymzh** [comment] 2016-04-11 01:31
Hey @swt2c - mhgui stuff?

**Comment by swt2c** [comment] 2016-04-11 03:04
Phil is correct - the Harmony 300 requires using mhgui.  The problem that you noted above is due to a Logitech change.  It's been fixed in git, but the problem is still exists in unstable - I need to fix that.  I'll see about fixing Jessie, too, but I'm not sure if Debian will consider this a serious enough bug to allow an update.  So, in the meantime, you can use the git version, or wait for an update.

**Comment by develroo** [comment] 2016-04-11 10:53
>  So, in the meantime, you can use the git version, 

There is a git for congruity? That is what mhgui is part of right? I thought it was only on [Sourceforge](https://sourceforge.net/projects/congruity/) and appears to be stagnated. 

Is it a simple fix? Can I patch the Debian source by hand?

Thanks.

**Comment by swt2c** [comment] 2016-04-11 13:04
Yes, that's the project page.  There hasn't been a congruity release in a while, but development is still alive.

You need this commit:
https://sourceforge.net/p/congruity/code/ci/9ae53766b3a3344653c9f9bc9be1ea36f81eadd3/

**Comment by develroo** [comment] 2016-04-11 13:27
Ahh cool. OK .. will patch it myself then and see if it works :) 

Cheers.

**Comment by swt2c** [comment] 2016-04-13 01:22
I uploaded a fixed version to Debian unstable, if you haven't tried to patch it yourself already.

**Comment by develroo** [comment] 2016-04-13 08:58
> I uploaded a fixed version to Debian unstable, if you haven't tried to patch it yourself already.

Ahh cool. I did patch it myself but better if I track a repo in case other changes come along. I have to much experience of compiling packages by hand than then finding dependencies change, directories are removed, config files disappear etc etc. 

Thanks for the effort I appreciate it.

**Comment by jaymzh** [comment] 2016-04-14 07:35
Closing now. Feel free to re-open if you have problems.

**Closed as completed by jaymzh** 2016-04-14 07:35 UTC
