### ISSUE TITLE
Cannot add new device on http://members.harmony.com/EasyZapper

### ISSUE THREAD

**Issue by ghost** [jaymzh/concordance#10] opened 2015-10-29 19:02 UTC
System:
Ubuntu 14.04.2 LTS
Firefox 39.0 (Mozilla Firefox for Ubuntu - canonical 1.0)
firefox running as root using sudo (I find this is necessary to successfully access Harmony firmware)

Steps to reproduce:
1. Navigate to htp://members.harmony.com/EasyZapper and click "Next"
2. Log in
3. Click on "More Options"
4. Click on "Add a Device"
! EXPECTED: follow instructions to add a new device to my profile (i.e. just replaced my receiver recently)
! ACTUAL: dumped to "Routine Server Maintenance" page and logged out of website
http://members.harmonyremote.com/EasyZapper/ProcessCheckBrowser/CB_InvalidBrowser2.asp?ReturnUrl=%2FEasyZapper%2FNew%2FProcLogin%2FStart%2Easp%3FBrowserIsChecked%3DTrue%26ReturnUrl%3D%252E%252E%252FUserHome%252Easp%26Error%3DLoginRequired%26Logout%3DTrue&SkinId=Harmony&OS=Win

Perhaps I need my browser to spoof something else?
Apologies in advance if this is a noob issue. Sorry.

**Comment by jaymzh** [comment] 2015-10-29 19:19
That's new. The URL does claim InvalidBrowser, can you install the User Agent Switcher extension, and pick a UA claiming to be windows or mac and see if that helps?

**Comment by ghost** [comment] 2015-10-29 20:27
I just installed User Agent Switcher from:
http://chrispederick.com/work/user-agent-switcher/

Imported additional UA strings from https://raw.github.com/chrispederick/user-agent-switcher/master/development/source/content_common/useragentswitcher/xml/useragents.xml

(as mentioned in User Agent Switcher help http://chrispederick.com/work/user-agent-switcher/help/#defaults)

Tried UAs as follows (didn't see any Mac specific UA options):
- Internet Explorer 8
- Internet Explorer 10
- Chrome 4
- Chrome 21

Issue still occurs in each case.

ADDITIONAL: I did not notice this before, but it makes sense: When I first navigate to http://members.harmonyremote.com/EasyZapper, instead of being redirected to http://members.harmonyremote.com/EasyZapper/New/ProcLogin/Start.asp, rather I am immediately redirected as follows before ever logging in: 

http://members.harmonyremote.com/EasyZapper/ProcessCheckBrowser/CB_InvalidBrowser2.asp?ReturnUrl=%2FEasyZapper%2FNew%2FProcLogin%2FStart%2Easp%3FBrowserIsChecked%3DTrue%26ReturnUrl%3D%252E%252E%252FUserHome%252Easp%26Error%3DLoginRequired%26Logout%3DTrue&SkinId=Harmony&OS=Win

**Comment by ghost** [comment] 2015-10-29 20:30
I should also mention that I am able to successfully modify an existing menu using this software. The firmware is properly generated and applied to the remote, as long as only the existing hw profile is used.

The reported issue only occurs when trying to add a new device, which is particularly vexxing since that is the main thing I am trying to accomplish right now.

**Comment by swt2c** [comment] 2015-10-30 00:27
I can't reproduce this.  I can add devices fine w/ Firefox on Linux.  I would try clearing your cookies and try again.  Also, try updating Firefox - 39 is a bit out of date.

**Comment by ghost** [comment] 2015-10-30 22:28
I was hopeful, but... did apt-get dist-upgrade and broke a bunch of things.
Got those fixed and back into Firefox. Version 41.0.2 this time.
www.mozilla.org/firefox‎ confirms that I am "using the latest version of Firefox"

Went History -> Clear All History, Time range to clear = Everything
- Browsing and Download History - check
- Form and Search History - check
- Cookies - check
- Cache - check
- Active Logins - check
- Offline Website Data - check
- Site Preferences - check

Closed and restarted Firefox.
Issue persists.
I really wish that I could not reproduce this issue either. Sorry.

Also, when I do see the login page, it mentions that owners of Harmony Ultimate, Touch, Smart Control, and 600/650/700 must go to myharmony.com. I recently bought a 700 and added it to my profile a month or two ago, which was the last time it worked. Is is possible that by adding a newer remote, that I got into this mess?

When you say that you cannot reproduce this issue, which harmony remote are you using?

**Comment by swt2c** [comment] 2015-10-30 22:38
The account I was testing is a 688,

Wait a minute - you said "I recently bought a 700 and added it to my profile a month or two ago".  I'm pretty sure the members.harmonyremote.com site only supports one remote per account, so how did you "add it to your profile?"

**Comment by ghost** [comment] 2015-10-31 03:07
IIRC, had to remove the old one before I could add the new. Didn't have to modify any activities and these were flashed to the new remote verbatim without incident. I say IIRC because that was a couple of months ago.

**Comment by swt2c** [comment] 2015-10-31 03:18
Yeah, it sounds like maybe your account is messed up somehow.  I would just try creating a new one.

**Comment by jaymzh** [comment] 2017-05-28 06:31
@motorheadabega did creating a new account help? Are you still needing assistance?

**Comment by joelpet** [comment] 2018-03-30 16:31
I run into the same issue—I'm thrown out when clicking **Add a Device** and subsequently **Next >** at the *Routine System Maintenance* prompt, with a message saying "Session time out. Please log in again."

However, I noticed that it only happens as I try to add a sixth device; if I click the same **Add a Device** link when there are less than than five devices already added, then it works fine.

**Comment by jaymzh** [comment] 2018-03-30 16:35
OK, I'm gonna close this, as it doesn't seem to be a bug on our side. Thanks for the info, @joelpet

**Closed as completed by jaymzh** 2018-03-30 16:35 UTC
